name: upload artifact

on:
  workflow_run:
    workflows: ["CodeQL Advanced"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: playerdata
          path: ./playercsv.csv
    
